x-pegasus:
  apiLang: python
  createdBy: hamzasafri
  createdOn: 06-08-26T14:50:16Z
pegasus: 5.0.4
name: diamond-workflow
jobs:
- type: job
  name: preprocess
  id: ID0000001
  arguments:
  - --input
  - f.a
  - --output1
  - f.b1
  - --output2
  - f.b2
  uses:
  - lfn: f.b1
    type: output
    stageOut: true
    registerReplica: true
  - lfn: f.a
    type: input
  - lfn: f.b2
    type: output
    stageOut: true
    registerReplica: true
  profiles:
    condor:
      request_memory: 256
- type: job
  name: job1
  id: ID0000002
  arguments:
  - --input
  - f.b1
  - --output
  - f.c1
  uses:
  - lfn: f.b1
    type: input
  - lfn: f.c1
    type: output
    stageOut: true
    registerReplica: true
  profiles:
    condor:
      request_memory: 256
- type: job
  name: job2
  id: ID0000003
  arguments:
  - --input
  - f.b2
  - --output
  - f.c2
  uses:
  - lfn: f.c2
    type: output
    stageOut: true
    registerReplica: true
  - lfn: f.b2
    type: input
  profiles:
    condor:
      request_memory: 256
- type: job
  name: postprocess
  id: ID0000004
  arguments:
  - --input1
  - f.c1
  - --input2
  - f.c2
  - --output
  - f.d
  uses:
  - lfn: f.d
    type: output
    stageOut: true
    registerReplica: true
  - lfn: f.c2
    type: input
  - lfn: f.c1
    type: input
  profiles:
    condor:
      request_memory: 512
jobDependencies:
- id: ID0000001
  children:
  - ID0000002
  - ID0000003
- id: ID0000002
  children:
  - ID0000004
- id: ID0000003
  children:
  - ID0000004
